from django.conf.urls import url
from django.views.generic import TemplateView, DetailView, RedirectView
from freezingsimulation.views import (
    Index_View,
    Freezingsimu_View,
    Category_View,
    Article_View,
    User_View,  # , , AllView, SearchView,
    # ColumnView, , NewsView, TagView, CategoryView
)

urlpatterns = [
    url(r'^freezingsimulation/category/(?P<category>\w+)/$',
        Category_View.as_view(),
        name='freezingsimulation-category-detail-view'),
    url(r'^freezingsimulation/$',
        Index_View.as_view(),
        name='freezingsimulation-index-view'),
    url(r'^freezingsimulation/freezingsimu$',
        Freezingsimu_View.as_view(),
        name='freezingsimulation-simu-view'),
    url(r'^freezingsimulation/simu/$',
        Freezingsimu_View.simu,
        name='freezingsimulation-simu'),
    url(r'^freezingsimulation/article/(?P<id>\w+).html$',
        Article_View.as_view(),
        name='freezingsimulation-article-detail-view'),
    # url(r'^/all/$', AllView.as_view(), name='all-view'),
    # url(r'^/search/$', SearchView.as_view()),
    # url(r'^/login/$',
    #     TemplateView.as_view(template_name="blog/login.html"),
    #     name='login-view'),
    # url(r'^/register/$',
    #     TemplateView.as_view(template_name="blog/register.html"),
    #     name='register-view'),
    url(r'^freezingsimulation/go-to-django/$',
        RedirectView.as_view(url='http://djangoproject.com'),
        name='freezingsimulation-go-to-django'),
    url(r'^freezingsimulation/forgetpassword/$',
        TemplateView.as_view(
            template_name="freezingsimulation/forgetpassword.html"),
        name='freezingsimulation-forgetpassword-view'),
    # url(r'^/resetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
    #     TemplateView.as_view(template_name="blog/resetpassword.html"),
    #     name='resetpassword-view'),
    # url(r'^/column/(?P<column>\w+)/$',
    #     ColumnView.as_view(), name='column-detail-view'),
    url(r'^freezingsimulation/user/(?P<slug>\w+)$',
        User_View.as_view(),
        name='freezingsimulation-user-view'),
    # url(r'^/news/$', NewsView.as_view(), name='news-view'),
    # url(r'^/news/(?P<pk>\w+)$',
    #     DetailView.as_view(model=News), name='news-detail-view'),
    # url(r'^/tag/(?P<tag>\w+)/$', TagView.as_view(), name='tag-detail-view'),
]
